# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='no-slug', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_type',
            field=models.CharField(choices=[('A', 'Audio'), ('V', 'Video'), ('I', 'Image'), ('S', 'Status'), ('B', 'Blog'), ('P', 'Project')], default='B', max_length=2),
        ),
    ]
