# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170117_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_type',
            field=models.CharField(choices=[('A', 'Audio'), ('V', 'Video'), ('I', 'Image'), ('S', 'Status'), ('B', 'Blog'), ('P', 'Project'), ('M', 'Admin')], default='B', max_length=2),
        ),
    ]
